### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by stone** [agl/xmpp#1]
An example how to use the library would be nice.

Cheers, Fredrik

**Comment by flosse** [comment]
nevertheless a simple hello world example would be helpful :)

**Comment by mclark4386** [comment]
:+1: I'm trying to just write a simple app to send events from one service to another and I can't even get this to connect to my server :-/ I'm sure it's something I'm doing, but a simple, well explained example goes a LONG way!

**Comment by agl** [comment]
xmpp isn't really supposed to be used independently I'm afraid. It's just a support library for xmpp-client. It happens to be a separate package just because it's useful to structure xmpp-client that way and a separate repo because that's the way it started when rsc wrote the beginnings of it.

**Comment by flosse** [comment]
> xmpp isn't really supposed to be used independently I'm afraid.

that's a pity :(
